SELECT TOP (1000) [Application Number]
      ,[Form Nickname]
      ,[Form PDF]
      ,[Funding Year]
      ,[FCC Form 470 Status]
      ,[Allowable Contract Date]
      ,[Created Date Time]
      ,[Created By]
      ,[Certified Date Time]
      ,[Certified By]
      ,[Last Modified Date Time]
      ,[Last Modified By]
      ,[Billed Entity Number]
      ,[Billed Entity Name]
      ,[Organization Status]
      ,[Organization Type]
      ,[Applicant Type]
      ,[Website URL]
      ,[Latitude]
      ,[Longitude]
      ,[Billed Entity FCC Registration Number]
      ,[Billed Entity Address 1]
      ,[Billed Entity Address 2]
      ,[Billed Entity City]
      ,[Billed Entity State]
      ,[Billed Entity Zip Code]
      ,[Billed Entity Zip Code Ext]
      ,[Billed Entity Email]
      ,[Billed Entity Phone]
      ,[Billed Entity Phone Ext]
      ,[Number of Eligible Entities]
      ,[Contact Name]
      ,[Contact Address 1]
      ,[Contact Address 2]
      ,[Contact City]
      ,[Contact State]
      ,[Contact Zip]
      ,[Contact Zip Ext]
      ,[Contact Phone]
      ,[Contact Phone Ext]
      ,[Contact Email]
      ,[Technical Contact Name]
      ,[Technical Contact Title]
      ,[Technical Contact Phone]
      ,[Technical Contact Phone Ext]
      ,[Technical Contact Email]
      ,[Authorized Person Name]
      ,[Authorized Person Address]
      ,[Authorized Person City]
      ,[Authorized Person State]
      ,[Authorized Person Zip]
      ,[Authorized Person Zip Ext]
      ,[Authorized Person Phone Number]
      ,[Authorized Person Phone Number Ext]
      ,[Authorized Person Email]
      ,[Authorized Person Title]
      ,[Authorized Person Employer]
      ,[Category One Description]
      ,[Category Two Description]
      ,[Installment Type]
      ,[Installment Min Range Years]
      ,[Installment Max Range Years]
      ,[Request for Proposal Identifier]
      ,[State or Local Restrictions]
      ,[State or Local Restrictions Description]
      ,[Statewide State]
      ,[All Public Schools Districts]
      ,[All Non-Public schools]
      ,[All Libraries]
      ,[Form Version]
  FROM [whodini].[dbo].[usac]